/* Main.c file generated by New Project wizard
 *
 * Created:   Wed Mar 24 2021
 * Processor: PIC18F4520
 * Compiler:  HI-TECH C for PIC18
 */

#include <htc.h>

void main(void)
 {
   // Write your code here
   while (1)
      ;
 }